version: "3.9"

services:
  db:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - dev.env
      - apikeys.env
    depends_on:
      db:
        condition: service_healthy
